#ifndef JP_PLUGIN_GLOBAL_H
#define JP_PLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

// Apparently, export specifications are not really needed for plugins,
// something takes care of them automatically (probably moc). 
// For this reason, this is not included anywhere even though it was
// generated by the shared library project template.
#ifdef JP_PLUGIN_LIB
# define JP_PLUGIN_EXPORT Q_DECL_EXPORT
#else
# define JP_PLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // JP_PLUGIN_GLOBAL_H
